version: "3.7"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    command: >
      bash -c "uvicorn --host 0.0.0.0 --port 3000 main:app --reload --workers 1"

