"""empty message

Revision ID: 5875dbe49803
Revises: 
Create Date: 2021-10-09 18:40:39.887986

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = '5875dbe49803'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('sensor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_id'), 'measurement', ['id'], unique=False)
    op.create_index(op.f('ix_measurement_sensor_id'), 'measurement', ['sensor_id'], unique=False)
    op.create_index(op.f('ix_measurement_timestamp'), 'measurement', ['timestamp'], unique=False)
    op.create_index(op.f('ix_measurement_value'), 'measurement', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurement_value'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_timestamp'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_sensor_id'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_id'), table_name='measurement')
    op.drop_table('measurement')
    # ### end Alembic commands ###
